FROM ubuntu:latest

RUN apt-get update && apt-get install -y npm nodejs
RUN npm install -g dotenv @mistralai/mistralai express nodemon

EXPOSE 6969

WORKDIR /home
COPY ./entry.sh /.
ENTRYPOINT ["/bin/bash", "/home/entry.sh"]
CMD ["bash"]