name: Cargo Build

on:
  push:
  pull_request:

jobs:
  build_and_test:
    name: build const-const-const
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./const-const-const
    steps:
      - uses: actions/checkout@v3
      - run: rustup default stable
      - run: cargo build --verbose
